### ISSUE TITLE
API version change

### ISSUE THREAD

**Issue by tradel** [mcoffin/terraform-provider-localfile#3]
Looks like Terraform is gearing up for an API version change in the master branch. Following your installation instructions and then running `terraform`, I get an error:

```
Error configuring: 1 error(s) occurred:

* Incompatible API version with plugin. Plugin version: 3, Ours: 2
```

I was able to fix the problem by doing:

```
cd ~/go/src/github.com/hashicorp/terraform
git checkout v0.8.7
go build -o ~/go/bin/terraform-provider-localfile github.com/mcoffin/terraform-provider-localfile
```

Hope this helps.

**Comment by mcoffin** [comment]
@tradel I wasn't able to reproduce this locally, even with terraform from the master branch. How exactly are you compiling or otherwise getting the terraform binaries that are giving you problems?

If you upgraded terraform without re-compiling `terraform-provider-localfile`, then that would almost certainly cause the problem you were seeing, but I don't see why you would have to check out `v0.8.7` of terraform in order to make this plugin still work.

Here's some output I produced locally.

```
% ~/go/bin/terraform -version
Terraform v0.9.0-dev

% ~/go/bin/terraform apply
localfile_file.helloworld: Refreshing state... (ID: helloworld.txt)
localfile_file.helloworld: Creating...
  content: "" => "Hello, world!"
  path:    "" => "helloworld.txt"
localfile_file.helloworld: Creation complete

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate
```

**Comment by mcoffin** [comment]
Ahh, I see what happened here.

I made this project a while back, and since it was so simple, I didn't use `godep` or anything similar to version my dependencies (just terraform really).

As long as you build this plugin against terraform binaries that use the same version of the plugin API as what you plan to use when running terraform, you'll be fine.

So, in fact, what you did above is the correct solution to the problem!

**Comment by mcoffin** [comment]
@tradel I added some documentation to the README to hopefully help others with a similar problem in the future, but I'm going to leave the build system simple so that it's easy for others to perform these kinds of version upgrades on their own in a canonical manner.

Thanks for the help!

**Comment by tradel** [comment]
@mcoffin Not everyone wants to run the bleeding edge of terraform, which is what `go get` would give you. 

Most package managers currently install Terraform 0.8.7, which is API v2, but by importing `github.com/hashicorp/terraform`, you're pulling in Terraform 0.9.0-dev (as your output above shows), which is API v3.
